database:
  host: localhost
  user: root
  password: 123456
  port: 3306
  database: ehx
pioneer:
  name: name
  pwd: pwd
todo_user:
  name: 17198642616
  pwd: TANRUIKAI888
exercise:
  # The eid at the beginning of the exercises, the eid of the first set of exercises that you have to do in each class
  start_eid: 292025
  # The eid at the end of the exercises, the eid of the last set of exercises to be done in each class
  end_eid: 292058
api:
  # the account name of http://www.ttshitu.com/
  uname: kai
  # the account password of http://www.ttshitu.com/
  pwd: 123
