# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build
      run: |
        python3 setup_gui.py build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe.linux-x86_64-3.10
        path: ./build/

    - name: create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release 1.0.0
        body: |
          This is the first release of my Python application.
        draft: false
        prerelease: false
#    - name: upload release asset
#      uses: actions/upload-release-asset@v1.0.2
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#      with:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        asset_path: ./build/
#        asset_name: exe.linux-x86_64-3.10
#        asset_content_type: application/zip

    - name: Attach Artifact to Release
        uses: actions/upload-release-asset@v1.0.2
        with:
          asset_path: ${{ github.workspace }}/build/
          asset_name: exe.linux-x86_64-3.10.zip
          asset_content_type: application/zip
          release_id: ${{ steps.create_release.outputs.release_id }}
          github_token: ${{ secrets.GH_TOKEN }}
